### ISSUE TITLE
Help, please.

### ISSUE THREAD

**Issue by zarkank** [Auscent/Tibia-11-SpriteDump#1]
Would you know how to put the same format again?
I'm trying to add new sprites on client 11
Could you help me?

**Comment by benjaminkomen** [comment]
I don't understand your question, what do you want to achieve?

**Comment by Auscent** [comment]
Converting back into the sprite format is beyond the scope of this project, however the basic idea would be to convert the image into a 32-bit BMP file and compress that using LZMA (preferably using the same coder properties as the original sprite files do) and stick the appropriate header data at the start. There may be issues with hash verification if you are trying to use it on CIP's server which I wouldn't recommend trying to do anyway with BattlEye being active, for custom servers you should be in control of the assets catalog so you can fix up the hashes and appropriately modify the catalog-content.json and appearances.dat files if you are adding entirely new sprites (which is my assumption). Anyway like I said it's beyond the scope of this project so that's the extent of my help.
