### ISSUE TITLE
For version 11.49, and 11.50 test server the offest is 30 bytes instead of 6.

### ISSUE THREAD

**Issue by Sopel97** [Auscent/Tibia-11-SpriteDump#4]
https://github.com/Auscent/Tibia-11-SpriteDump/blob/eba7613c7eb962b57b0c2665141f351866e5430e/T11_SpriteDump/Program.cs#L128

I created a pull request.

**Comment by Auscent** [comment]
Thanks for bringing this to my attention, and sorry for the late reply. I've done some investigating myself and they seem to have made their header a constant 32 bytes in length and they align their 5-byte constant and the 7-bit encoded LZMA size at the end. This constant header size has the effect of when LZMA size is >= 16,384 bytes (>= 16,416 full file size) as this value will get encoded into 3 bytes which will push the LZMA offset to 29 instead of 30, so using a constant offset of 30 will result in an incorrect LZMA size being read in cases of such large files (nearly half) which isn't necessarily a big issue if you are ignoring the size like this dumper is. Still I would rather my code try to reflect this so I will update it to use a dynamic approach of looping through the NULL bytes until the constant is reached, an advantage of this would be support for both the older and newer files with potential compatibility with future changes.
